import Link from "next/link";
import styles from "./page.module.css"
import "./../app/global.css"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <header className={styles.header}>
          <div className={styles.header__name}>
            <p>🪓</p>
            <h3>George Contreras</h3>
          </div>
          <nav className={styles.header__nav}>
            <ul>
              <li><Link href={"/"}>Home</Link></li>
              <li><Link href={"/"}>Projects</Link></li>
              <li><Link href={"/"}>Articles</Link></li>
              <li><Link href={"/"}>Contact</Link></li>
            </ul>
          </nav>
        </header>
        {children}
        <footer className={styles.footer}>@ all rights reserved 2025</footer>
      </body>
    </html>
  );
}
